#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-aiosmtpd
Version  : 1.4.4.post2
Release  : 17
URL      : https://files.pythonhosted.org/packages/10/c0/6bcf406e244ddbd83bbde5d3e009f2a2e8e5872883e229e30e2d307afa2c/aiosmtpd-1.4.4.post2.tar.gz
Source0  : https://files.pythonhosted.org/packages/10/c0/6bcf406e244ddbd83bbde5d3e009f2a2e8e5872883e229e30e2d307afa2c/aiosmtpd-1.4.4.post2.tar.gz
Summary  : aiosmtpd - asyncio based SMTP server
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-aiosmtpd-bin = %{version}-%{release}
Requires: pypi-aiosmtpd-license = %{version}-%{release}
Requires: pypi-aiosmtpd-python = %{version}-%{release}
Requires: pypi-aiosmtpd-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(atpublic)
BuildRequires : pypi(attrs)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=========================================
aiosmtpd - An asyncio based SMTP server
=========================================

%package bin
Summary: bin components for the pypi-aiosmtpd package.
Group: Binaries
Requires: pypi-aiosmtpd-license = %{version}-%{release}

%description bin
bin components for the pypi-aiosmtpd package.


%package license
Summary: license components for the pypi-aiosmtpd package.
Group: Default

%description license
license components for the pypi-aiosmtpd package.


%package python
Summary: python components for the pypi-aiosmtpd package.
Group: Default
Requires: pypi-aiosmtpd-python3 = %{version}-%{release}

%description python
python components for the pypi-aiosmtpd package.


%package python3
Summary: python3 components for the pypi-aiosmtpd package.
Group: Default
Requires: python3-core
Provides: pypi(aiosmtpd)
Requires: pypi(atpublic)
Requires: pypi(attrs)

%description python3
python3 components for the pypi-aiosmtpd package.


%prep
%setup -q -n aiosmtpd-1.4.4.post2
cd %{_builddir}/aiosmtpd-1.4.4.post2
pushd ..
cp -a aiosmtpd-1.4.4.post2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674148741
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-aiosmtpd
cp %{_builddir}/aiosmtpd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-aiosmtpd/2a4d8f324098b4a0c006aa8e4cc445c940e68861 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/aiosmtpd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-aiosmtpd/2a4d8f324098b4a0c006aa8e4cc445c940e68861

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
